spring:
#  profiles:
#    active: ${profile}
  application:
    name: ssm_3
     
  devtools: #devtools
    restart:
      enabled: true
  
  datasource:
    url: jdbc:mariadb://localhost:3306/ssm # 환경변수 DB_URL로부터 URL 동적으로 받기
    username: root # 환경변수 DB_USERNAME로부터 사용자명 받기
    password: 1234 # 환경변수 DB_PASSWORD로부터 비밀번호 받기
    driver-class-name: org.mariadb.jdbc.Driver
#    jndi-name: ${DB_JNDI_NAME}
#    type: basic


  jpa:
    hibernate:
      ddl-auto: none # Hibernate가 DDL을 실행하지 않도록 설정
      show-sql: true
      format_sql: true # SQL 출력 시 보기 좋게 포맷팅
    properties:
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl  # 기본 JPA 네이밍 전략
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # 물리적 네이밍 전략
    database-platform: org.hibernate.dialect.MariaDBDialect
  
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT}
#            client-secret: ${GOOGLE_SECRET}
#            scope:  # google API의 범위 값
#              - profile 
#              - email 
#          kakao:
#          client-id: 
#          client-secret: 
#            redirect-uri: {baseUrl}/login/oauth2/code/kakao
#            client-authentication-method: client_secret_post # kakao는 인증 토큰 발급 요청 메서드가 post이다. (최근 버전에는 작성 방법이 이렇게 바뀌었다.)
#            authorization-grant-type: authorization_code
#            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
#              - profile_nickname
#              - profile_image
#              - account_email
#            client-name: kakao

      # kakao provider 설정
#      provider:
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#      user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명으로 해야 한다.

server:
  port: 8081

#mybatis:
#  configuration:
#    multiple-result-sets-enabled: false
#    map-underscore-to-camel-case: true
#    call-setters-on-nulls: true
#    jdbc-type-for-null: varchar
#    default-fetch-size: 500
#  mapper-locations:
#  - classpath:mybatis/**/*.xml

####################################################################################################################################################
# logging
####################################################################################################################################################
logging:
  level:
    root: debug
  file:
    name: local
    path: C:/logs
  config: classpath:logback-spring.xml
  pattern:
    console: "[%.-1level][%-19.19d{yyMMdd HH:mm:ss:SSS}][%-21.21thread] - [%X{traceId}] - [%-60.60c][%-20.20M:%4.4line] - %msg%n"
    file: "[%.-1level][%-19.19d{yyMMdd HH:mm:ss:SSS}][%-21.21thread] - [%X{traceId}] - [%-60.60c][%-20.20M:%4.4line] - %msg%n"
  logback:
    rollingpolicy:
      max-history: 1


####################################################################################################################################################
# Swagger
####################################################################################################################################################
springdoc:
  api-docs:
    path: /swagger-ui.html
    groups:
      enabled: true 
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    tags-sorter: alpha