spring:
  application:
    name: ssm_3
  config:
    activate:
      on-profile: local
  devtools: #devtools
    restart:
      enabled: true

server:
  port: 8081
  
####################################################################################################################################################
# logging
####################################################################################################################################################
logging:
  level:
    root: debug
  file:
    name: local
    path: C:/logs
  config: classpath:logback-spring.xml
  pattern:
    console: "[%.-1level][%-19.19d{yyMMdd HH:mm:ss:SSS}][%-21.21thread] - [%X{traceId}] - [%-60.60c][%-20.20M:%4.4line] - %msg%n"
    file: "[%.-1level][%-19.19d{yyMMdd HH:mm:ss:SSS}][%-21.21thread] - [%X{traceId}] - [%-60.60c][%-20.20M:%4.4line] - %msg%n"
  logback:
    rollingpolicy:
      max-history: 1



####################################################################################################################################################
# Swagger
####################################################################################################################################################
springdoc:
  api-docs:
    path: /swagger-ui
    groups:
      enabled: true 
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    tags-sorter: alpha